include: package:lints/recommended.yaml

analyzer:
  exclude:
    - "build/**"
    - "test/**.mocks.dart"
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    # Additional rules
    always_declare_return_types: true
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    prefer_final_locals: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    unnecessary_brace_in_string_interps: true
    use_key_in_widget_constructors: true