name: backend
description: Modern Dart Backend with Clean Architecture
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.5
  shelf_static: ^1.1.2
  http: ^1.2.1
  dart_jsonwebtoken: ^2.14.0
  bcrypt: ^1.1.3
  crypto: ^3.0.3
  dotenv: ^4.2.0
  yaml: ^3.1.2
  validators: ^3.0.0
  meta: ^1.12.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  logging: ^1.2.0
  intl: ^0.19.0
  postgres: ^3.5.6

dev_dependencies:
  test: ^1.25.8
  lints: ^4.0.0
  coverage: ^1.8.0
  mockito: ^5.4.4
  build_runner: ^2.4.9

executables:
  server: server